name: Release
on: [push]

jobs:
  release:
    name: Release Keycloak Extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and Push Image
        with:
          image: keycloak-extensions
          registry: ghcr.io
          dockerfile: keycloak-extensions/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
