name: Release
on:
  push:
    paths:
    - 'nodered/**'

jobs:
  release:
    name: Release Node Red
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and Push Image
        with:
          image: nodered
          registry: ghcr.io
          dockerfile: nodered/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
